services:
  - couchdb
language: elixir
elixir:
  - 1.2.6
  - 1.3.4
  - 1.4.2
otp_release:
  - 18.2
  - 19.0
script:
  - "MIX_ENV=test mix run priv/repo/seeds.exs"
  - "MIX_ENV=test mix do deps.get, deps.compile, test --trace"
